import type { Component } from "./model";
const part = (
  id: string,
  name: string,
  category: string,
  manufacturer: string,
  parameters: Component["parameters"],
  source: string,
  description: string,
  verified = true,
): Component => ({
  id,
  name,
  category,
  manufacturer,
  parameters,
  source,
  description,
  verified,
  official: true,
});
export const CATALOG: Component[] = [
  part("powerfilm-ll200-24-75", "LL200-2.4-75 · 非晶硅默认", "pv", "PowerFilm", {chemistry:"a-Si", areaCm2:68.62, referenceLux:200, densityUwCm2:289/68.62, voltage:1.6}, "https://www.powerfilmsolar.com/hubfs/documents/spec%20sheets/electronic%20component%20solar%20panels/electronic%20component%20solar%20panels%20spec%20sheet_indoor%20light%20series.pdf", "200 lux: 289 µW, 1.6 V; 94 × 73 mm. Density uses module footprint. Spectrum/angle scaling and LDO dropout are design assumptions."),
  part("assumed-opv-leh3", "OPV · LEH3_50x20_6_10 演算模板", "pv", "Epishine / PowerMatch assumptions", {chemistry:"OPV", areaCm2:10, referenceLux:500, densityUwCm2:16.7, voltage:2.5}, "https://kb.epishine.com/wp-content/uploads/2021/08/LEH3-Data-Sheet.pdf", "500 lux warm white LED: 167 µW over 10 cm² module. Working voltage 2.5 V is a simulation assumption, NOT the 3.8 V open-circuit specification.", false),
  part("assumed-perovskite", "钙钛矿 · 通用演算模板（待实测）", "pv", "PowerMatch assumptions", {chemistry:"Perovskite", areaCm2:20, referenceLux:200, densityUwCm2:5, voltage:2.5}, "", "All electrical values are illustrative assumptions, not Saule specifications or a verified purchasable model.", false),
  part("assumed-lic-1f", "LIC 1F · 演算模板（待选型）", "lic", "PowerMatch assumptions", {farads:1, voltage:3.8, maxVoltage:3.8, minVoltage:2.5, leakUa:3, esr:1}, "", "1 F requested default. Voltage, leakage and ESR are assumptions requiring actual part validation.", false),
  part("assumed-li-ion-40mah", "锂电池 40mAh · 演算模板", "rechargeable", "PowerMatch assumptions", {voltage:3.7, capacityMah:40, maxVoltage:4.2, minVoltage:3, leakUa:1, esr:1}, "", "Illustrative rechargeable battery; all values require selected cell validation.", false),
  part("assumed-harvester-regulator", "采能充电 + 稳压 · 演算模板", "pmic", "PowerMatch assumptions", {iqUa:0.5, efficiency:0.8, harvestEfficiency:0.8, mppt:"Yes", charger:"Yes"}, "", "Functional system template, not a single validated IC. Charger thresholds, cold start, output voltage and external parts require engineering verification.", false),
  part(
    "panasonic-cr2032",
    "CR2032",
    "battery",
    "Panasonic",
    { voltage: 3, capacityMah: 225, minVoltage: 2 },
    "https://energy.panasonic.com/dam/master/pdf/en/datasheet/lithium/CR2032_Datasheet_EN.pdf",
    "Lithium primary; capacity depends on load, temperature and cutoff.",
  ),
  part(
    "murata-cr2032",
    "CR2032",
    "battery",
    "Murata",
    { voltage: 3, capacityMah: 220, minVoltage: 2 },
    "https://www.murata.com/-/media/webrenewal/products/batteries/micro/cr/standard/ds-cr2032-003-je_202307.ashx?la=en-us",
    "Standard discharge 0.2 mA. Primary, not rechargeable.",
  ),
  part(
    "panasonic-cr2450",
    "CR2450",
    "battery",
    "Panasonic",
    { voltage: 3, capacityMah: 620, minVoltage: 2 },
    "https://energy.panasonic.com/dam/master/pdf/en/datasheet/lithium/CR2450_Datasheet_EN.pdf",
    "24.5 × 5.0 mm. Pulse sag needs verification.",
  ),
  part(
    "panasonic-cr2477",
    "CR2477",
    "battery",
    "Panasonic",
    { voltage: 3, capacityMah: 1000, minVoltage: 2 },
    "https://energy.panasonic.com/na/business/products/lithium/coin-cr-standard/models/CR2477",
    "24.5 × 7.7 mm. Primary cell.",
  ),
  part(
    "maxell-lr41",
    "LR41",
    "battery",
    "Maxell",
    { voltage: 1.5, capacityMah: 25, minVoltage: 1.2 },
    "https://biz.maxell.com/en/primary_batteries/SRLR_22e.pdf",
    "25 mAh at 70 µA, 20°C, cutoff 1.2 V.",
  ),
  part(
    "gp-lr41",
    "GP192 / LR41",
    "battery",
    "GP",
    { voltage: 1.5, capacityMah: 24, minVoltage: 1.2 },
    "https://ind.gpbatteries.com/pub/media/wysiwyg/Primary_Batteries/041023_Primary%2BCatalogue_Final.pdf",
    "Capacity uses GP catalog conditions.",
  ),
  part(
    "maxell-lr44",
    "LR44",
    "battery",
    "Maxell",
    { voltage: 1.5, capacityMah: 110, minVoltage: 1.2 },
    "https://biz.maxell.com/en/primary_batteries/SRLR_22e.pdf",
    "110 mAh at 100 µA, 20°C, cutoff 1.2 V.",
  ),
  part(
    "gp-lr44",
    "A76 / LR44",
    "battery",
    "GP",
    { voltage: 1.5, capacityMah: 110, minVoltage: 1.2 },
    "https://ind.gpbatteries.com/pub/media/wysiwyg/Primary_Batteries/041023_Primary%2BCatalogue_Final.pdf",
    "Primary alkaline button cell.",
  ),
  part(
    "energizer-a76",
    "A76 / LR44",
    "battery",
    "Energizer",
    { voltage: 1.5, capacityMah: null },
    "https://data.energizer.com/pdfs/a76.pdf",
    "Select usable capacity from the load-specific discharge curve.",
  ),
  part(
    "energizer-aa",
    "E91 / AA / LR6",
    "battery",
    "Energizer",
    { voltage: 1.5, capacityMah: null, minVoltage: 0.8 },
    "https://data.energizer.com/pdfs/e91.pdf",
    "AA alkaline. Enter usable capacity for the actual discharge and cutoff.",
  ),
  part(
    "energizer-aaa",
    "E92 / AAA / LR03",
    "battery",
    "Energizer",
    { voltage: 1.5, capacityMah: null, minVoltage: 0.8 },
    "https://data.energizer.com/pdfs/e92.pdf",
    "AAA alkaline. Capacity is not a fixed chemistry-independent value.",
  ),
  part(
    "capxx-lic10",
    "LY13R808014M106R-L",
    "lic",
    "CAP-XX",
    { farads: 10, maxVoltage: 3.8, minVoltage: 2.5, leakUa: 3, esr: 0.8 },
    "https://cap-xx-assets.s3.eu-west-2.amazonaws.com/CAP_XX_LY_13_R8_LIC_Datasheet_V1_7_b24dfbf553.pdf",
    "LIC 10 F; DC ESR 800 mΩ, maximum leakage 3 µA after 120 h.",
  ),
  part(
    "capxx-lic25",
    "LY13R808020M256R-L",
    "lic",
    "CAP-XX",
    { farads: 25, maxVoltage: 3.8, minVoltage: 2.5, leakUa: null, esr: null },
    "https://cap-xx-assets.s3.eu-west-2.amazonaws.com/CAP_XX_LY_13_R8_LIC_Datasheet_V1_7_b24dfbf553.pdf",
    "25 F LIC. Model-specific leakage and ESR still need review.",
    false,
  ),
  part(
    "capxx-edlc1",
    "GY12R708012V105R",
    "supercap",
    "CAP-XX",
    { farads: 1, maxVoltage: 2.7, minVoltage: 0.1, leakUa: 2, esr: 0.25 },
    "https://cap-xx-assets.s3.eu-west-2.amazonaws.com/CAP_XX_GY_series_Datasheet_V4_5_776c24ea2c.pdf",
    "EDLC, not LIC. Maximum leakage 2 µA after 72 h. Lower operating cutoff is design-dependent.",
  ),
  part(
    "tps7a02",
    "TPS7A02 / 1.5 V",
    "ldo",
    "Texas Instruments",
    { iqUa: 0.025, mppt: "No", inputMin: 1.5, inputMax: 6 },
    "https://www.ti.com/lit/ds/symlink/tps7a02.pdf",
    "Typical Iq 25 nA; exact order code, dropout, capacitors and startup need verification.",
  ),
  part(
    "aem10941",
    "AEM10941",
    "pmic",
    "e-peas",
    { mppt: "Yes", efficiency: null },
    "https://e-peas.com/documents/AEM10941/DS-AEM10941.pdf",
    "Solar harvesting PMIC. Configure storage thresholds and actual efficiency curves.",
  ),
  part(
    "bq25570",
    "BQ25570",
    "pmic",
    "Texas Instruments",
    { mppt: "Yes", efficiency: null },
    "https://www.ti.com/lit/ds/symlink/bq25570.pdf",
    "Energy harvesting charger with buck converter; cold-start and voltage limits apply.",
  ),
  ...["MKS3061", "MKS3062", "MKS3162"].map((name) =>
    part(
      name.toLowerCase(),
      name,
      "pmic",
      "Makesense",
      { mppt: "Unverified", efficiency: null },
      "https://www.makesensic.com/ProductInfoCategory?categoryId=1060443&PageInfoId=1879234",
      "Official catalog confirmed. Full electrical specification pending.",
      false,
    ),
  ),
  part(
    "powerfilm-indoor",
    "Indoor Light Series",
    "pv",
    "PowerFilm",
    { chemistry: "a-Si", densityUwCm2: null },
    "https://www.powerfilmsolar.com/hubfs/documents/spec%20sheets/electronic%20component%20solar%20panels/electronic%20component%20solar%20panels%20spec%20sheet_indoor%20light%20series.pdf",
    "Choose a specific module, spectrum and measurement curve.",
    false,
  ),
  part(
    "epishine-leh3",
    "LEH3",
    "pv",
    "Epishine",
    { chemistry: "OPV", densityUwCm2: null },
    "https://kb.epishine.com/wp-content/uploads/2021/08/LEH3-Data-Sheet.pdf",
    "Organic indoor PV. Original PDF retrieval currently unavailable.",
    false,
  ),
  part(
    "saule-ppv",
    "PPV.IOT",
    "pv",
    "Saule",
    { chemistry: "Perovskite", densityUwCm2: null },
    "https://sauletech.com/wp-content/uploads/2025/01/Product-Catalog-Saule.pdf",
    "Perovskite indoor PV. Source file pending.",
    false,
  ),
  part(
    "ixolar",
    "IXOLAR",
    "pv",
    "IXYS / Littelfuse",
    { chemistry: "Monocrystalline Si", densityUwCm2: null },
    "https://www.littelfuse.com",
    "Candidate family only. Specific module and indoor curves required.",
    false,
  ),
  part(
    "powerfoyle",
    "Powerfoyle",
    "pv",
    "Exeger",
    { chemistry: "DSSC", densityUwCm2: null },
    "https://www.exeger.com/powerfoyle/downloads/",
    "Customized indoor / hybrid modules require individual calibration.",
    false,
  ),
  part(
    "tiny-lcd",
    "MOT-U125 · LCD",
    "display",
    "ZenMeasure",
    { minVoltage: 1.2, maxVoltage: 1.65 },
    "/assets/specs/MOT-U125-v2.1-20260616.jpg",
    "Whole product brochure. Below 1.2 V invisible and above 1.8 V ghosting are user observations; internal IC spec pending.",
    false,
  ),
  part(
    "mho-eink",
    "MHO-C404 · E-paper",
    "display",
    "ZenMeasure",
    { productVoltage: 3, refreshEnergy: null },
    "/assets/specs/MHO-C404-v1.1-20260907.jpg",
    "Product voltage is not the bare panel voltage. E-paper retains stale data when power is lost.",
    false,
  ),
  ...[
    "resistor",
    "capacitor",
    "inductor",
    "diode",
    "load-switch",
    "supervisor",
    "connector",
    "rechargeable",
  ].map((category) =>
    part(
      `custom-${category}`,
      `Custom ${category}`,
      category,
      "Custom",
      { value: null },
      "",
      "Enter manufacturer part number and operating parameters. No assumed engineering approval.",
      false,
    ),
  ),
];
