-- Preserve the original incomplete public Tiny record as revision 1.
-- Revision 2 is a source-linked, conditional PowerFilm example; it is not a Tiny field measurement.
INSERT INTO revisions(id,case_id,number,design_json,engine_version,parent_revision,scope)
SELECT 'tiny-demo-r2',id,2,'{"name":"穿山甲Tiny · 光伏改型","device":"MOT-U125","load":{"voltage":1.5,"minVoltage":1.2,"maxVoltage":1.65,"phases":[{"name":"Sleep","seconds":9,"currentUa":3},{"name":"Active","seconds":1.2,"currentUa":90}]},"mode":"pv","path":"ldo","light":{"source":"office","lux":260,"days":5,"hours":10,"startHour":9,"angle":0,"planeMeasured":false},"pv":{"componentId":"powerfilm-ll200-24-75","areaCm2":68.62,"referenceLux":200,"densityUwCm2":4.211600116584086,"voltage":1.6,"utilization":0.7},"storage":{"kind":"primary","componentId":"panasonic-cr2032","series":1,"parallel":1,"voltage":3,"capacityMah":225,"farads":null,"maxVoltage":3,"minVoltage":2,"initialPercent":100,"leakUa":0,"esr":20},"regulation":{"componentId":"tps7a02","iqUa":0.025,"dropout":0.1,"efficiency":0.8,"harvestEfficiency":0.8,"mppt":false,"charger":false},"horizonDays":30,"margin":20,"notes":"MOT-U125: 11+ µA is an engineering estimate. Timing model: 13.2353 µA. 150 lux is a prior test observation, not a universal threshold. Internal IC and original LR41 ×2 wiring are unconfirmed. 演算假设 / Simulation assumptions: battery ESR 20 ohm; regulator dropout 0.1 V; conversion/harvest efficiency 80%; non-MPPT utilization 70%. Validate at actual operating conditions. PowerFilm 200 lux power density uses module footprint, not active cell area.","parameterSources":{"pv.areaCm2":{"kind":"catalog","reference":"powerfilm-ll200-24-75"},"pv.referenceLux":{"kind":"catalog","reference":"powerfilm-ll200-24-75"},"pv.densityUwCm2":{"kind":"catalog","reference":"powerfilm-ll200-24-75"},"pv.voltage":{"kind":"catalog","reference":"powerfilm-ll200-24-75"},"storage.capacityMah":{"kind":"catalog","reference":"panasonic-cr2032"},"storage.minVoltage":{"kind":"catalog","reference":"panasonic-cr2032"},"storage.voltage":{"kind":"catalog","reference":"panasonic-cr2032"},"storage.esr":{"kind":"assumption","detail":"20 Ω simulation input"},"regulation.iqUa":{"kind":"catalog","reference":"tps7a02"},"regulation.dropout":{"kind":"assumption"},"regulation.efficiency":{"kind":"assumption"},"regulation.harvestEfficiency":{"kind":"assumption"},"pv.utilization":{"kind":"assumption"}}}','0.1.0','tiny-demo-r1','public'
FROM cases
WHERE id='tiny-demo' AND latest_revision=1
  AND EXISTS (SELECT 1 FROM revisions WHERE id='tiny-demo-r1' AND case_id='tiny-demo');

UPDATE cases SET latest_revision=2,updated_at=CURRENT_TIMESTAMP
WHERE id='tiny-demo' AND latest_revision=1
  AND EXISTS (SELECT 1 FROM revisions WHERE id='tiny-demo-r2' AND case_id='tiny-demo');
