import assert from 'node:assert/strict';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
import {randomBytes,createHash} from 'node:crypto';
import {DEFAULT_DESIGN} from '../src/shared/model.ts';
const base='http://127.0.0.1:8787';
const origin='http://127.0.0.1:5173';
const suffix=randomBytes(5).toString('hex');
const identities=['employee','outsider','colleague'].map((role,i)=>({id:`test-${role}-${suffix}`,email:`test-${suffix}-${i}@${i===1?'example.test':'zenmeasure.com'}`,token:randomBytes(32).toString('hex')}));
const sql=identities.map(u=>`INSERT INTO users(id,email,display_name) VALUES('${u.id}','${u.email}','Test'); INSERT INTO sessions(token_hash,user_id,expires_at) VALUES('${createHash('sha256').update(u.token).digest('hex')}','${u.id}',${Math.floor(Date.now()/1000)+900});`).join('\n');
fs.mkdirSync('tmp',{recursive:true});fs.writeFileSync('tmp/test-identities.sql',sql);
execFileSync(process.execPath,['node_modules/wrangler/bin/wrangler.js','d1','migrations','apply','powermatch-db','--local'],{stdio:'pipe',env:{...process.env,WRANGLER_LOG_PATH:'tmp/test-wrangler.log'}});
execFileSync(process.execPath,['node_modules/wrangler/bin/wrangler.js','d1','execute','powermatch-db','--local','--file=tmp/test-identities.sql'],{stdio:'pipe',env:{...process.env,WRANGLER_LOG_PATH:'tmp/test-wrangler.log'}});
let assertions=0;
async function request(path,{user,method='GET',data,cookie,expected=200,sendOrigin=true}={}){const r=await fetch(base+path,{method,headers:{...(sendOrigin?{Origin:origin}:{}),...(user?{Cookie:`pm_session=${user.token}`} :cookie?{Cookie:cookie}:{}),...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined});assert.equal(r.status,expected,`${method} ${path}: ${r.status}`);assertions++;return {data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
const [employee,outsider,colleague]=identities;
const linkToken=randomBytes(32).toString('hex');
fs.writeFileSync('tmp/test-link.sql',`INSERT INTO login_tokens(token_hash,email,locale,expires_at) VALUES('${createHash('sha256').update(linkToken).digest('hex')}','${employee.email}','zh',${Math.floor(Date.now()/1000)+600});`);
execFileSync(process.execPath,['node_modules/wrangler/bin/wrangler.js','d1','execute','powermatch-db','--local','--file=tmp/test-link.sql'],{stdio:'pipe',env:{...process.env,WRANGLER_LOG_PATH:'tmp/test-wrangler.log'}});
await request('/api/auth/consume',{method:'POST',data:{token:linkToken}});
await request('/api/auth/consume',{method:'POST',data:{token:linkToken},expected:401});
await request('/api/admin',{expected:403});
await request('/api/admin',{user:employee,expected:403});
await request('/api/cases?scope=private',{user:outsider,expected:403});
await request('/api/calculate',{method:'POST',data:DEFAULT_DESIGN,sendOrigin:false,expected:403});
const guest=(await request('/api/session')).cookie;
const create=(scope)=>({name:`API verification ${suffix}`,scope,design:DEFAULT_DESIGN});
await request('/api/cases',{method:'POST',cookie:guest,data:create('private'),expected:403});
const priv=(await request('/api/cases',{method:'POST',user:employee,data:create('private')})).data;
await request('/api/cases/'+priv.id,{expected:404});await request('/api/cases/'+priv.id,{user:colleague,expected:404});
await request('/api/posts',{method:'POST',user:employee,data:{type:'revision',target:priv.revisionId,body:'Private revision evidence'}});
const pub=(await request('/api/cases',{method:'POST',user:employee,data:{...create('public'),id:priv.id,expectedRevision:1}})).data;
const publicRead=(await request('/api/cases/'+pub.id)).data;assert.equal(publicRead.revisions.length,1);assert.equal(publicRead.revisions[0].number,2);assertions+=2;
await request('/api/posts?type=revision&target='+priv.revisionId,{expected:404});
await request('/api/cases',{method:'POST',user:outsider,data:{...create('public'),parentRevision:priv.revisionId},expected:404});
await request('/api/cases',{method:'POST',user:employee,data:{...create('public'),id:priv.id,expectedRevision:1},expected:409});
await request('/api/cases/'+pub.id,{method:'DELETE',user:outsider,expected:404});
const own=(await request('/api/cases/'+pub.id,{user:employee})).data;assert.equal(own.revisions.length,2);assertions++;
const guestCase=(await request('/api/cases',{method:'POST',cookie:guest,data:create('public')})).data;
await request('/api/cases/'+guestCase.id,{method:'DELETE',expected:404});
await request('/api/cases/'+guestCase.id,{method:'DELETE',cookie:guest});
await request('/api/cases/'+pub.id,{method:'DELETE',user:employee});
console.log(JSON.stringify({test:'local API authorization and revisions',assertions,result:'passed',externalEmailsSent:0}));
